name: Call Reusable Workflow

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Reusable Workflow
        uses: devops-dabu/reusable/.github/workflows/reusable-lab.yml@main
        with:
          workflow: 'reusable-workflow.yml'
          required-secret: ${{ secrets.MY_REQUIRED_SECRET }}
