name: Reusable Lab

on:
  push:
    branches:
      - main

jobs:
  reusable-job:
    runs-on: ubuntu-latest

    steps:
    - name: Imprimir mensaje desde reusable-lab.yml
      uses: devops-dabu/reusable/.github/workflows/reusable-lab.yml@main
      run: |
        echo "Este es un mensaje desde el flujo de trabajo reusable-lab.yml"
        echo "Mensaje secreto: ${{ secrets.MI_SECRETO }}"
