name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  main-job:
    runs-on: ubuntu-latest

    steps:
    - name: Imprimir mensaje desde main-workflow.yml
      run: echo "Este es un mensaje desde el flujo de trabajo main-workflow.yml"

  main-job-with-secret:
    runs-on: ubuntu-latest
    needs: main-job

    steps:
    - name: Ejecutar flujo de trabajo reusable
      uses: devops-dabu/reusable/.github/workflows/reusable-lab.yml@main
      with:
        MI_SECRETO: ${{ secrets.MI_SECRETO }}
