name: Requirements

on:
  push:
    branches: [laboratory, main]

jobs:
  triage:
    uses: devops-dabu/reusable/.github/workflows/reusable-lab.yml@main
    with:
        repo-token: ${{ secrets.token }}
        configuration-path: ${{ inputs.config-path }}

