name: Requirements
on:
  push:
    branches: [laboratory, main]
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Validar secret
      env:
        TITLE: ${{ secret.GITHUB }}
        run: |
          if [[ "$TITLE" =~ ^crni ]]; then
          echo "Token Valido"
          exit 0
          else
          echo "Token INvalido"
          exit 1
          fi  

    - name: Ejecutar flujo de trabajo reusable
      uses: devops-dabu/reusable/.github/workflows/reusable-lab.yml@main
      with:
        secreto-entrada: ${{ secrets.MI_SECRETO }} # Pasamos el secreto al flujo de trabajo reusable
