name: Requirements
on:
  push:
    branches: [laboratory, main]
jobs:
  triage:
    uses: devops-dabu/reusable/.github/workflows/reusable-lab.yml@main
    with:
      secrets: |
        MI_SECRETO=${{ secrets.MI_SECRETO }}
