name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Reusable Workflow
        uses: devops-dabu/reusable/.github/workflows/reusable-lab.yml@main
        with:
          secret-token: ${{ secrets.MY_SECRET }}
